services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb?schema=public
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - app-network

  studio:
    image: node:22.11.0-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: npx prisma studio --port 5555 --browser none
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb?schema=public
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:


networks:
  app-network:
